#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ldap3
Version  : 2.8.1
Release  : 15
URL      : https://files.pythonhosted.org/packages/72/b9/b358e58d113928080b2cfaeb49078cdbcb33854886166afd325563219aef/ldap3-2.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/72/b9/b358e58d113928080b2cfaeb49078cdbcb33854886166afd325563219aef/ldap3-2.8.1.tar.gz
Summary  : A strictly RFC 4510 conforming LDAP V3 pure Python client library
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: ldap3-license = %{version}-%{release}
Requires: ldap3-python = %{version}-%{release}
Requires: ldap3-python3 = %{version}-%{release}
Requires: pyasn1
BuildRequires : buildreq-distutils3
BuildRequires : pyasn1

%description
=====

%package license
Summary: license components for the ldap3 package.
Group: Default

%description license
license components for the ldap3 package.


%package python
Summary: python components for the ldap3 package.
Group: Default
Requires: ldap3-python3 = %{version}-%{release}

%description python
python components for the ldap3 package.


%package python3
Summary: python3 components for the ldap3 package.
Group: Default
Requires: python3-core
Provides: pypi(ldap3)
Requires: pypi(pyasn1)

%description python3
python3 components for the ldap3 package.


%prep
%setup -q -n ldap3-2.8.1
cd %{_builddir}/ldap3-2.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599599384
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ldap3
cp %{_builddir}/ldap3-2.8.1/COPYING.LESSER.txt %{buildroot}/usr/share/package-licenses/ldap3/93a34ec120cdc2f9216d2217ffb32908fd9e3d4b
cp %{_builddir}/ldap3-2.8.1/COPYING.txt %{buildroot}/usr/share/package-licenses/ldap3/52be821be7d06dde87d7805331066d1af6f3f9f8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ldap3/52be821be7d06dde87d7805331066d1af6f3f9f8
/usr/share/package-licenses/ldap3/93a34ec120cdc2f9216d2217ffb32908fd9e3d4b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
